name: binaries2
on: [workflow_dispatch]

env:
  ALPINE_BRANCH: v3.18
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JOBS: 3
  CFLAGS: -Os -fomit-frame-pointer -pipe
  LINUX_LDFLAGS: -static -Wl,--as-needed -Wl,-Map,linker.map
  DARWIN_LDFLAGS: -Wl,-map,linker.map
  WIN32_LDFLAGS: -Wl,--as-needed -Wl,-Map,linker.map
  # List of extra nginx modules to download.
  # NOTE: nginx/njs is not defined here, but directly in the jobs.
  NGINX_MODULES: >-
    kjdev/nginx-auth-jwt
    kjdev/nginx-keyval
    vision5/ngx_devel_kit
    openresty/echo-nginx-module
    openresty/headers-more-nginx-module
    openresty/set-misc-nginx-module
  # The same as above, but for Windows.
  # - kjdev/nginx-auth-jwt, kjdev/nginx-keyval: a bit complicated to build (TODO)
  NGINX_MODULES_WIN32: >-
    vision5/ngx_devel_kit
    openresty/echo-nginx-module
    openresty/headers-more-nginx-module
    openresty/set-misc-nginx-module
  # Don't update binaries with unchanged sources.
  SKIP_SAME_SOURCES: true

jobs:
  nginx-multi-linux:
    name: nginx-${{ matrix.NGINX_VERSION }}-${{ matrix.ARCH }}-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NGINX_VERSION:
          - 1.24.x
          - 1.25.x
          - 1.26.x
        ARCH:
          - x86_64
          - aarch64
          - ppc64le
        include:
          # - NJS_VERSION: 0.x.x
          # Pin older njs version for old stable nginx.
          - NGINX_VERSION: 1.24.x
            NJS_VERSION: 0.8.x
    steps:
      - name: Checkout sbh branch
        uses: actions/checkout@v4
        with:
          path: sbh

      - name: Download and extract nginx
        run: ./sbh/scripts/fetch-sources -d . nginx/nginx@release-${{ matrix.NGINX_VERSION }}

      - name: Download and extract nginx modules
        run: ./sbh/scripts/fetch-sources nginx/njs@${{ matrix.NJS_VERSION }} $NGINX_MODULES

      - name: Install Alpine ${{ env.ALPINE_BRANCH }} for ${{ matrix.ARCH }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.ARCH }}
          branch: ${{ env.ALPINE_BRANCH }}
          packages: >
            build-base
            jansson-dev
            jansson-static
            linux-headers
            openssl-dev
            openssl-libs-static
            pcre-dev
            zlib-dev
            zlib-static

      - name: Build nginx
        env:
          NGINX_MODULES: ${{ env.NGINX_MODULES }}
          CFLAGS: ${{ env.CFLAGS }}
          LDFLAGS: ${{ env.LINUX_LDFLAGS }}
        run: ./sbh/scripts/build-nginx
        shell: alpine.sh {0}

      - name: Upload nginx binary to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nginx-${{ matrix.NGINX_VERSION }}-${{ matrix.ARCH }}-linux
          path: artifact/*
